"""correction ProductName

Revision ID: 2bb883c848cb
Revises: ba27262c71ac
Create Date: 2025-08-21 20:47:37.351105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb883c848cb'
down_revision: Union[str, Sequence[str], None] = 'ba27262c71ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('productName', sa.String(), nullable=True))
    op.drop_column('submissions', 'product_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('product_name', sa.VARCHAR(), nullable=True))
    op.drop_column('submissions', 'productName')
    # ### end Alembic commands ###
