"""empty message

Revision ID: 568f99c4692c
Revises: ff70387abf34
Create Date: 2025-08-22 04:09:54.780322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568f99c4692c'
down_revision: Union[str, Sequence[str], None] = 'ff70387abf34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('ocr_ingredients_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'ocr_ingredients_text')
    # ### end Alembic commands ###
