"""Création de la structure de base de données initiale

Revision ID: 68a234beef2a
Revises: f42a4cbd1fc9
Create Date: 2025-08-01 17:54:25.724993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a234beef2a'
down_revision: Union[str, Sequence[str], None] = 'f42a4cbd1fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
