"""add_subcategory_to_products

Revision ID: 6b78b19c92b5
Revises: 06bc9217495c
Create Date: 2026-01-27 00:57:10.068656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b78b19c92b5'
down_revision: Union[str, Sequence[str], None] = '06bc9217495c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produits', sa.Column('subcategory', sa.String(), nullable=True))
    op.alter_column('submissions', 'ocr_nutrition_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'ocr_nutrition_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('produits', 'subcategory')
    # ### end Alembic commands ###
