"""Creation de la table pending_additifs

Revision ID: 6f6c66fd7f52
Revises: b25aad9913f0
Create Date: 2025-10-22 18:15:38.555858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6c66fd7f52'
down_revision: Union[str, Sequence[str], None] = 'b25aad9913f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additifs_pending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('e_code', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('e_code')
    )
    op.create_index(op.f('ix_additifs_pending_id'), 'additifs_pending', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_additifs_pending_id'), table_name='additifs_pending')
    op.drop_table('additifs_pending')
    # ### end Alembic commands ###
