"""notri-score to nutriscore

Revision ID: 7151fa4e87c1
Revises: 714a20ca76f7
Create Date: 2025-09-11 03:14:52.954029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7151fa4e87c1'
down_revision: Union[str, Sequence[str], None] = '714a20ca76f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produits', sa.Column('nutri_score', sa.String(), nullable=True))
    op.drop_column('produits', 'nutriscore')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produits', sa.Column('nutriscore', sa.VARCHAR(), nullable=True))
    op.drop_column('produits', 'nutri_score')
    # ### end Alembic commands ###
