"""Ajout des colonnes de scoring a la table produits

Revision ID: 81d9012fcd04
Revises: 568f99c4692c
Create Date: 2025-09-10 18:54:42.123939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d9012fcd04'
down_revision: Union[str, Sequence[str], None] = '568f99c4692c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produits', sa.Column('nutriscore', sa.String(), nullable=True))
    op.add_column('produits', sa.Column('nova_group', sa.Integer(), nullable=True))
    op.add_column('produits', sa.Column('ecoscore_grade', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produits', 'ecoscore_grade')
    op.drop_column('produits', 'nova_group')
    op.drop_column('produits', 'nutriscore')
    # ### end Alembic commands ###
