"""ajoute de parsed_nutriments dans Submission

Revision ID: ade16a5c5ec8
Revises: 7151fa4e87c1
Create Date: 2025-09-12 04:38:53.890086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade16a5c5ec8'
down_revision: Union[str, Sequence[str], None] = '7151fa4e87c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('parsed_nutriments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'parsed_nutriments')
    # ### end Alembic commands ###
