"""structure_initiale

Revision ID: b25aad9913f0
Revises: 
Create Date: 2025-09-27 04:58:17.877054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25aad9913f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('additifs_e_number_key'), 'additifs', type_='unique')
    op.drop_index(op.f('ix_additifs_e_number'), table_name='additifs')
    op.create_index(op.f('ix_additifs_e_number'), 'additifs', ['e_number'], unique=True)
    op.add_column('submissions', sa.Column('found_additives', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'found_additives')
    op.drop_index(op.f('ix_additifs_e_number'), table_name='additifs')
    op.create_index(op.f('ix_additifs_e_number'), 'additifs', ['e_number'], unique=False)
    op.create_unique_constraint(op.f('additifs_e_number_key'), 'additifs', ['e_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
