"""Ajout de nom et marque aux soumissions

Revision ID: ba27262c71ac
Revises: 3f5db6b45ec9
Create Date: 2025-08-21 20:04:51.350580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba27262c71ac'
down_revision: Union[str, Sequence[str], None] = '3f5db6b45ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('product_name', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('brand', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'brand')
    op.drop_column('submissions', 'product_name')
    # ### end Alembic commands ###
