"""Ajout image tableau nutritionnel

Revision ID: d95df8751789
Revises: 01ee4659df12
Create Date: 2025-12-04 18:39:45.392979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95df8751789'
down_revision: Union[str, Sequence[str], None] = '01ee4659df12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('image_nutrition_url', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('ocr_nutrition_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'ocr_nutrition_text')
    op.drop_column('submissions', 'image_nutrition_url')
    # ### end Alembic commands ###
