"""Rendre la colonne typeProduct optionnelle

Revision ID: f42a4cbd1fc9
Revises: 95d23cfa7e49
Create Date: 2025-08-01 17:01:11.377427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42a4cbd1fc9'
down_revision: Union[str, Sequence[str], None] = '95d23cfa7e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
