"""ajoute de sin et ins dans additif

Revision ID: f4d756015072
Revises: 6f6c66fd7f52
Create Date: 2025-10-23 13:44:01.975355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d756015072'
down_revision: Union[str, Sequence[str], None] = '6f6c66fd7f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additifs', sa.Column('sin_number', sa.String(), nullable=True))
    op.add_column('additifs', sa.Column('ins_number', sa.String(), nullable=True))
    op.alter_column('additifs', 'e_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('additifs_pending', sa.Column('sin_number', sa.String(), nullable=True))
    op.add_column('additifs_pending', sa.Column('ins_number', sa.String(), nullable=True))
    op.drop_constraint(op.f('additifs_pending_e_code_key'), 'additifs_pending', type_='unique')
    op.create_index(op.f('ix_additifs_pending_e_code'), 'additifs_pending', ['e_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_additifs_pending_e_code'), table_name='additifs_pending')
    op.create_unique_constraint(op.f('additifs_pending_e_code_key'), 'additifs_pending', ['e_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('additifs_pending', 'ins_number')
    op.drop_column('additifs_pending', 'sin_number')
    op.alter_column('additifs', 'e_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('additifs', 'ins_number')
    op.drop_column('additifs', 'sin_number')
    # ### end Alembic commands ###
